name: CI
description: Runs Continuous Integration
runs:
    using: composite
    steps:
        - name: Setup PNPM
          uses: pnpm/action-setup@v4

        - name: Setup Node.js
          uses: actions/setup-node@v5
          with:
              cache: 'pnpm'
              node-version-file: '.tool-versions'
              cache-dependency-path: 'pnpm-lock.yaml'
              scope: '@dnd-mapp'
              registry-url: 'https://npm.pkg.github.com'

        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile

        - name: Check formatting
          shell: bash
          run: pnpm format:check

        - name: Check linting
          shell: bash
          run: pnpm lint

        - name: Compile code
          shell: bash
          run: pnpm build

        - name: Run tests
          shell: bash
          run: |
              playwright install chromium
              pnpm test
